import 'package:movin/domain/entities/property_model.dart';

List<PropertyModel> dummyProperties = [
  PropertyModel(
    id: 1,
    title: "Modern Luxury Villa",
    location: "Dubai Marina",
    image: "assets/images/villa3.jpg",
    tag: "sale",
    price: "1,250,000 EGP",
    beds: 4,
    baths: 3,
    sqft: 3500,
  ),
  PropertyModel(
    id: 2,
    title: "Skyline Apartment",
    location: "New York City",
    image: "assets/images/villa3.jpg",
    tag: "rent",
    price: "4,500 EGP / month",
    beds: 3,
    baths: 2,
    sqft: 1800,
  ),
  PropertyModel(
    id: 3,
    title: "Commercial Office Space",
    location: "Cairo Downtown",
    image: "assets/images/villa3.jpg",
    tag: "commercial",
    price: "850,000 EGP",
    beds: 0,
    baths: 0,
    sqft: 5000,
  ),
  PropertyModel(
    id: 4,
    title: "Investment Villa",
    location: "Bali",
    image: "assets/images/villa3.jpg",
    tag: "investment",
    price: "960,000 EGP",
    beds: 5,
    baths: 4,
    sqft: 4200,
  ),
  PropertyModel(
    id: 5,
    title: "Modern Luxury Villa",
    location: "Dubai Marina",
    image: "assets/images/villa3.jpg",
    tag: "sale",
    price: "1,250,000 EGP",
    beds: 4,
    baths: 3,
    sqft: 3500,
  ),
  PropertyModel(
    id: 6,
    title: "Skyline Apartment",
    location: "New York City",
    image: "assets/images/villa3.jpg",
    tag: "rent",
    price: "4,500 EGP / month",
    beds: 3,
    baths: 2,
    sqft: 1800,
  ),
  PropertyModel(
    id: 7,
    title: "Commercial Office Space",
    location: "Cairo Downtown",
    image: "assets/images/villa3.jpg",
    tag: "commercial",
    price: "850,000 EGP",
    beds: 0,
    baths: 0,
    sqft: 5000,
  ),
  PropertyModel(
    id: 8,
    title: "Investment Villa",
    location: "Bali",
    image: "assets/images/villa3.jpg",
    tag: "investment",
    price: "960,000 EGP",
    beds: 5,
    baths: 4,
    sqft: 4200,
  ),
  PropertyModel(
    id: 9,
    title: "Modern Luxury Villa",
    location: "Dubai Marina",
    image: "assets/images/villa3.jpg",
    tag: "sale",
    price: "1,250,000 EGP",
    beds: 4,
    baths: 3,
    sqft: 3500,
  ),
  PropertyModel(
    id: 10,
    title: "Skyline Apartment",
    location: "New York City",
    image: "assets/images/villa3.jpg",
    tag: "rent",
    price: "4,500 EGP / month",
    beds: 3,
    baths: 2,
    sqft: 1800,
  ),
  PropertyModel(
    id: 11,
    title: "Commercial Office Space",
    location: "Cairo Downtown",
    image: "assets/images/villa3.jpg",
    tag: "commercial",
    price: "850,000 EGP",
    beds: 0,
    baths: 0,
    sqft: 5000,
  ),
  PropertyModel(
    id: 12,
    title: "Investment Villa",
    location: "Bali",
    image: "assets/images/villa3.jpg",
    tag: "investment",
    price: "960,000 EGP",
    beds: 5,
    baths: 4,
    sqft: 4200,
  ),
  PropertyModel(
    id: 13,
    title: "Modern Luxury Villa",
    location: "Dubai Marina",
    image: "assets/images/villa3.jpg",
    tag: "sale",
    price: "1,250,000 EGP",
    beds: 4,
    baths: 3,
    sqft: 3500,
  ),
  PropertyModel(
    id: 14,
    title: "Skyline Apartment",
    location: "New York City",
    image: "assets/images/villa3.jpg",
    tag: "rent",
    price: "4,500 EGP / month",
    beds: 3,
    baths: 2,
    sqft: 1800,
  ),
  PropertyModel(
    id: 15,
    title: "Commercial Office Space",
    location: "Cairo Downtown",
    image: "assets/images/villa3.jpg",
    tag: "commercial",
    price: "850,000 EGP",
    beds: 0,
    baths: 0,
    sqft: 5000,
  ),
  PropertyModel(
    id: 16,
    title: "Investment Villa",
    location: "Bali",
    image: "assets/images/villa3.jpg",
    tag: "investment",
    price: "960,000 EGP",
    beds: 5,
    baths: 4,
    sqft: 4200,
  ),
];
